### ISSUE TITLE
Використав наслідування, дуже добре)

### ISSUE THREAD

**Issue by Rainbowdm** [bpm2021/auth_Polvanov_g2#1]
https://github.com/bpm2021/auth_Polvanov_g2/blob/453f835a483c69816170b3a4408d266dfaaa8a10/src/test/java/web/BaseTest.java#L7

**Comment by bpm2021** [comment]
Дякую за коментар! У наступному домашньому завданні буду наслідувати методи(наприклад, setup(), який буде ініціалізовувати об`єкт driver)
